### ISSUE TITLE
Toggling without selecting a word will toggle only a subset of the word if it matched first

### ISSUE THREAD

**Issue by Pnoexz** [HiDeoo/toggler-vscode#1]
Repro:
    * Open new file
    * Type _inner_
    * Place cursor between I and N
    * Toggle

Expected:
Word is now _outer_

Actual:
Word is now _outner_, because it toggled _in_ first instead of _inner_

**Comment by HiDeoo** [comment]
Should be fixed in the next update whenever that is.
