### ISSUE TITLE
toggleable notification

### ISSUE THREAD

**Issue by d0ob** [HiDeoo/toggler-vscode#14]
Hi there ! 

I was wondering if the notification could be disabled, could it be possible to have a setting for that ? 

Anyway, damn cool extension ! So practical, very very handy ! Thanks much !

**Comment by HiDeoo** [comment]
First, thanks for you review, really appreciated.

Just to be sure, are we talking about the notification that appears only when you try to use the extension on a word not having any toggles?

<img width="475" alt="Screenshot 2021-09-24 at 07 41 35" src="https://user-images.githubusercontent.com/494699/134624292-78761c40-2fa5-40d9-947a-147c6c7ad0f7.png">

Or is there some other notification that I may not be aware of?

If we're talking about the one in the screenshot, I don't personally hit this one a lot but I guess I'm not against adding a setting (defaulting to `true`) for this.

**Comment by d0ob** [comment]
My pleasure, it's well worth it !  

Yes, those notifications. =) I don't have them all day either ^^ But I still miss-shortcut sometimes.. And they are very long, maybe even permanent until closed ? I'd prefer the shortcut to do nothing if it can't do anything. It's not a pain, it's a nitpicking demand, take action only if easy/quick to do ! Notification on by default is perfect =)

Thanks for your quick answer, in any case !

**Comment by HiDeoo** [comment]
Ok, I totally see the point, and indeed I have no control over the duration. I'm ok with adding a small setting for this. 

I'm not sure when I'll get to it exactly but it's in my todo list.

I'll make sure to ping this issue when it's done.

**Comment by d0ob** [comment]
Excellent, thanks for considering ! 
No problem, there is no hurry =) I stay tuned ^^

**Comment by HiDeoo** [comment]
A new version `0.4.0` containing this feature has just been published 🎉 

<img width="538" alt="Screenshot 2022-03-19 at 18 55 23" src="https://user-images.githubusercontent.com/494699/159132784-ec80342b-c5b5-48f9-ac27-7ed34ede7d7d.png">
