### ISSUE TITLE
Toggle surrounding characters while inside the expression

### ISSUE THREAD

**Issue by remusa** [HiDeoo/toggler-vscode#15]
Would it be possible to have this toggle the next surrounding pair from the inside (without having to move to the desired character first).

What I mean is something like the [Toggle Quotes](https://github.com/BriteSnow/vscode-toggle-quotes) extension. Basically you can be inside a string and press the key bind and it will cycle through the available quote characters without having to move to the opening/closing quote. This could also work from inside parenthesis, brackets, etc.

Example:

''Hello [cursor] world'' -> `Hello [cursor] world` -> 'Hello [cursor] world'
[hi there] -> {hi there}

**Comment by HiDeoo** [comment]
Thanks for your feedback.

I use a [similar extension](https://marketplace.visualstudio.com/items?itemName=vilicvane.es-quotes) and tried at some point to mimic their behavior in this extension altho after multiple attempts, I decided that this was a not a good idea.

Implementing such behavior had various undesirable side effects, specially with text selections, or would even break basic features of the extension. I thought about adding this special changes only for single characters replacements or even symbols, but that would break the existing behavior for some users. I thought about adding some special shortcuts modifiers to active this new behavior but this was becoming a mess for the end-user. This was even becoming annoying when you wanted to toggle a word in a quoted sentence as there was no predictable way to know what the user wanted.

I think it's best to keep this totally different kind of toggles in two extensions, specially considering how small they are and their low impact on activation time.
