### ISSUE TITLE
Feature request: add  a option or shortcut to "toggle-reverse",thanks

### ISSUE THREAD

**Issue by shawn-yee** [HiDeoo/toggler-vscode#16]
left->center->right
left<-center<-right

**Comment by HiDeoo** [comment]
I'm not sure I see the point of adding such a command considering that if you continue pressing the toggle shortcut, it'll loop back infinitely.

For example, with `test1` -> `test2` -> `test3`, pressing the toggle shortcut after `test3` will cycle back to `test1`:

![demo](https://user-images.githubusercontent.com/494699/159128710-0d03ed87-5704-49d3-a9fd-73133d77ed6e.gif)

If the goal in your example was going back to `left` from `right`, pressing the shortcut one more time will bring you back to `test1`, which is even faster than a potential `toggle-reverse` command.

**Comment by shawn-yee** [comment]
["flex-start", "center", "flex-end", "space-around", "space-evenly", "space-between"]

A more accurate example above, because sometimes your options will be greater than three, and my current toggle shortcut is cmd+t, when adding a cmd+shift+t, it will be more convenient to use, if it is difficult to implement this feature, it is not necessary

**Comment by shawn-yee** [comment]
@HiDeoo Anyway, thanks for your plugin, which I used every day, it's great

**Comment by HiDeoo** [comment]
> ["flex-start", "center", "flex-end", "space-around", "space-evenly", "space-between"]
> 
> A more accurate example above, because sometimes your options will be greater than three, and my current toggle shortcut is cmd+t, when adding a cmd+shift+t, it will be more convenient to use, if it is difficult to implement this feature, it is not necessary

I see, that makes more sense. I'm usually having toggles with 2 or 3 words on a daily basis so didn't thought about this use-case. 

I may not have the time on the short term to implement this right now, but I just added this to my todo list for the next version. 

Without too much thinking, the implementation shouldn't be too difficult. I'll prolly add this as a new command like you suggested which wouldn't have a shortcut assigned by default, and let user assign a key combos to it if they do want to do so.

I'll make sure to ping this issue with progress or when this is released.

**Comment by HiDeoo** [comment]
> I'll make sure to ping this issue with progress or when this is released.

A bit late to the party but the feature is finally available in the version `0.5.0` that I just published thanks to a PR from @Kotsuha :tada:
