### ISSUE TITLE
Toggling on a camel case word should not handle sub-words that don't follow the camel case

### ISSUE THREAD

**Issue by batanun** [HiDeoo/toggler-vscode#3]
First of all: Great plugin! :)

Now, here is my bug report:

The text: "setInformation"
Toggle-configuration for the word "information": not set
Cursor position: after the last n character
Expected toggle result: <no change>
Actual result: "setInformatioff"

I think that when it detects a mix of cases (ie not all upper or all lower case) it should only identify words on camel case intersections (or non word characters, like dashes etc). So the word "Information" above should not be divided into sub parts.

Or, if this change would break some other functionally, that I don't know about, maybe add the possibility to configure this.

**Comment by HiDeoo** [comment]
Thanks!

Some users, including me, relies on the plugin working over word boundaries when the plugin is in a camel case context.

Considering that if a user wants to toggle `setInformation` or `information`, a user can still configure that behavior, I don't really see the point of adding an option for this case, altho, I'll keep monitoring that request if some other people would like this and re-evaluate if needed.
