### ISSUE TITLE
Removing/replacing defaults

### ISSUE THREAD

**Issue by certainlyakey** [HiDeoo/toggler-vscode#5]
Hi! Thanks for the great plugin. 

I'd like to remove the default toggles from the config — they are a bit of a nuisance since many of them are partially the same as mine (for example i have `['body', 'header']` which conflicts with the default `['body', 'head']`). Is it possible?

**Comment by AlansCodeLog** [comment]
I too just ran into a similar problem. I wanted `off` to toggle to `warn` or `error` for setting eslint config values, but it only ever toggles between `on` and `off`.

**Comment by HiDeoo** [comment]
The next version will include an option to not use the default toggles so they can be 100% customized by the user through the settings.

<img width="557" alt="Screenshot 2020-05-29 at 12 08 02" src="https://user-images.githubusercontent.com/494699/83251546-0b0af080-a1aa-11ea-87a0-a7e59a50e826.png">
